version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///src/database/app.db}
    volumes:
      - ./src/database:/app/src/database
    restart: unless-stopped

  # Optional: PostgreSQL database
  # Uncomment if you want to use PostgreSQL instead of SQLite
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: presh_ai_training
  #     POSTGRES_USER: presh_user
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:

